.TH ddns-ipfwo-conf 8
.SH NAME
ddns-ipfwo-conf \- set up ddns-ipfwo for use with supervise/svscan
.SH SYNOPSIS
.B ddns-ipfwo-conf
.I acct logacct D ddnsddir 
.SH DESCRIPTION
.B ddns-ipfwo-conf
creates a service directory 
.I D 
that runs 
.BR ddns-ipfwo (8) .
The name 
.I D 
must start with a slash and must not contain any special characters. 
.P
You can run the service under 
.BR svscan(8)
by creating a symbolic link in the 
.I /service 
directory to
.IR D .
.P
The service will start within five seconds, and will be restarted 
upon reboot. You can use svc to control the service. 
.P
.B ddns-ipfwo-conf
arranges  
.BR ddns-ipfwo (8) 
to chroot to 
.I ddnsddir
and to create files under the uid and gid of 
.IR acct .
.BR ddns-ipfwo (8) 
will
.I not
drop root privileges.

.I ddnsddir
is the directory hierachy where ddns is 
.IR chroot () ed 
too, typically /service/ddnsd/root/.
.I acct 
should be the same account as 
.BR ddnsd (8) 
uses.
.P
.B ddns-cleand-conf
creates an automatically rotated log directory in 
.IR D /log/main. 
The logs are owned by 
.IR logacct . 
The corrosponding 
.BR multilog (8) 
processes will run under the uid and gid of 
.IR logacct . 
The name
.I logacct 
must not contain any special characters. 
.SH BUGS
The
.B run
Skript does not handle flushing of chains and so on. 
.SH AUTHOR
Doobee R. Tzeck <drt@un.bewaff.net>
.SH SEE ALSO
ddns-ipfwo(8),
supervise(8),
svc(8),
svscan(8),
multilog(8),
tai64nlocal(8),
envuidgid(8),
softlimit(8),
http://un.bewaff.net/ddns/
