.TH ddns-pipe 5
.SH NAME
ddns-pipe \- format used by the ddns system for IPC
.SH DESCRIPTION
.IR ddnsd (8)
and
.IR ddns-snapd (8)
use this format to send information to various tools like
.IR ddns-ipfwo (8).
via named pipes.
.P
The format can express IPv4, IPv6, DNS LOC, uid and hostname data beeing
added, removed and expired. It also can express renewing uids.  
.SH "THE DDNS-PIPE FORMAT"
A ddns-pipe command stream consists of commands seperated by 
.IR \\n.
Each line starts with a byte defining the command followed by an arbitary 
amount of data bytes followd by a newline. The databytes can contain
all values other then 
.IR \\n.
There are four types of commands
(1) setentry; (2) killentry; (3) expireentry; (4) renewentry.
.TP 5
(1)
A 
.B setentry
command begins with 
.I `s'
followed by a decimal userid followed by
.IR `,' ,
a dotted decimal IPv4 address,
.IR `,' ,
a coloned hexadecimal IPv6 address,
.IR `,' ,
an encoded DNS LOC record,
.I `,' 
and a hostname. For more Information on the LOC record see
.IR ddns-file (5).

Example:
.EX
     s1199,127.0.0.1,0:0:0:0:0:0:0:0,50 57 9.700 N 6 54 8.300 E 5700 5000 5000 1000,me.dyn.rc23.cx
.EE

A setentry command is sent when ddnsd recived a new registration from a client.

.TP 5
(2)
A 
.B killentry
command begins with 
.I `k'
followed by the same data as a 
.I setentry 
command.

A killentry command is sent when a client requested removal of its data.

.TP 5
(3)
A 
.B expireentry
command begins with 
.I `e'
followed by the same data as a 
.I setentry 
command.

A expireentry command is sent when a the server removes client data. This is done by 
.IR ddns-cleand (8).

.TP 5
(4) 
A 
.B renewentry
command beginns with
.I `r'
followed by a decimal usreid.

Example:
.EX
     r1199
.EE

An renewentry command is send, when a client renews the leasetime of its entry.
.P
.SH "AUTHOR"
Doobee R. Tzeck <drt@ailis.de> is to blame for this.
.P
.SH "SEE ALSO"
ddnsd(8),
ddns-cleand(8),
ddns-snapd(8),
ddns-ipfwo(8)
