.TH filedns 8
.SH NAME
filedns \- dns server publishing a single zone
.SH SYNOPSIS
.B filedns 
.SH DESCRIPTION
.B filedns
is a server for serving single dns querys out of a single zone.
It reads its information out of a directory structure.
.P
Upon startup
.B filedns
binds to port 
.I UDP 
.IR 53 ,
.IR chroot (3)s
to the directory in the enviroment variable
.I $ROOT
and dorps it privileges to user
.I $UID
and group
.IR $GID .
.P
It then listens for incomming dns querys on port 53 UDP.
.P
To answer querys 
.B filedns
trys to open a file in a directory tree corrospondending  
to the dns tree. This means that information for
.I drt.dyn.rc23.cx
is searched in the file
.IR /cx/rc23/dyn/drt .
.P
The format of this files is described in 
.IR ddnsd-file (5).
.P
Recursive querys are discarded, querys for files/names which
filedns can't find are answered with NXDOMAIN.
.P
.B filedns logs to stderr. 
.IR multilog (8) 
is able to handle this well.
.P
.SH BUGS
The handling of authority is broken. A lot of other stuff is
broken. It delivers all the time not only the Information but
two additional TXT records "this is a response from an alpha
quality dns-server", "filednes 0.00 - if problems arise
contact drt@un.bewaff.net".
.B filedns
is not fully RfC complient.
.P
.SH AUTHOR
.B filedns
is written by Doobee R. Tzeck <drt@un.bewaff.net> heaviely 
borrowing code from Dan Bernsteins walldns.
.P
.SH SEE ALSO
multilog(8), ddnsd-data(8),
http://un.bewaff.net/ddns/
